name: atumonline
description: Atum Online
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular2: ^3.1.0
  jsonpadding: ^0.1.0
  stream_transform: ^0.0.6
dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  mockito: ^2.0.2
  test: ^0.12.21
transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'
            Client: 'package:http/http.dart'
web:
  compiler:
    debug: dartdevc
